# This yml file will trigger a Github Action on pushes to the main branch.
# This Action will build and upload a Docker image to Dockerhub
# https://github.com/marketplace/actions/publish-docker

name: dockerhub-publish

on:
  push:
    branches: 
    - main

jobs:
  main:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@master

    - name: Publish nuclear_data_base_docker to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: shimwell/nuclear_data_base_docker
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
